apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testrhoaichatbot-app 
  janus-idp.io/tekton: testrhoaichatbot-app
  backstage.io/kubernetes-id: testrhoaichatbot-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testrhoaichatbot-app
resources: 
- application-dev.yaml