apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testrhoaichatbot-app
  janus-idp.io/tekton: testrhoaichatbot-app
  backstage.io/kubernetes-id: testrhoaichatbot-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testrhoaichatbot-app
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/