---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testrhoaichatbot-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testrhoaichatbot-app 
  name: testrhoaichatbot-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi